-- 알림 시스템 1라운드(기능) 스키마. 설계: README.md §4
-- 접수 원장(request) / 채널·디바이스별 전달(delivery)을 분리한다.

CREATE TABLE app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(320),
    phone   VARCHAR(32)
);

CREATE TABLE device (
    device_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT       NOT NULL REFERENCES app_user(user_id),
    token     VARCHAR(512) NOT NULL,
    platform  VARCHAR(16)  NOT NULL,
    active    BOOLEAN      NOT NULL DEFAULT TRUE,
    last_seen TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_device_token UNIQUE (token)
);

CREATE TABLE notification_setting (
    setting_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user(user_id),
    channel    VARCHAR(16) NOT NULL,
    category   VARCHAR(32) NOT NULL,
    enabled    BOOLEAN     NOT NULL,
    CONSTRAINT uq_setting UNIQUE (user_id, channel, category)
);

CREATE TABLE template (
    template_id VARCHAR(64)  PRIMARY KEY,
    channel     VARCHAR(16),
    category    VARCHAR(32)  NOT NULL,
    priority    VARCHAR(16)  NOT NULL DEFAULT 'normal',
    locale      VARCHAR(16),
    version     INT          NOT NULL DEFAULT 1,
    subject     VARCHAR(255),
    body        VARCHAR(4000) NOT NULL
);

CREATE TABLE notification_request (
    request_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user(user_id),
    category   VARCHAR(32) NOT NULL,
    priority   VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification_delivery (
    delivery_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT       NOT NULL REFERENCES notification_request(request_id),
    channel       VARCHAR(16)  NOT NULL,
    target        VARCHAR(512) NOT NULL,
    status        VARCHAR(16)  NOT NULL,
    attempt_count INT          NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_delivery_request ON notification_delivery(request_id);
