-- 라운드 B(신뢰성): 멱등 + Transactional Outbox. 설계: README.md §6-1
-- 기존 V1 은 수정하지 않고 신규 마이그레이션으로 추가한다.

-- 멱등: (producer_id, dedup_key) 단위로 중복 접수를 1건으로 흡수.
-- dedup_key 가 NULL 이면 멱등 미적용(Postgres UNIQUE 는 NULL 을 서로 distinct 로 취급).
ALTER TABLE notification_request
    ADD COLUMN producer_id VARCHAR(64)  NOT NULL DEFAULT 'default',
    ADD COLUMN dedup_key   VARCHAR(128);

ALTER TABLE notification_request
    ADD CONSTRAINT uq_request_dedup UNIQUE (producer_id, dedup_key);

-- Outbox: request/delivery 와 같은 트랜잭션으로 커밋되어 "저장됐는데 큐엔 안 들어감"(dual-write 유실)을 막는다.
-- 릴레이가 PENDING 을 읽어 provider 로 발행하고 PUBLISHED 로 표시한다.
-- payload(channel/target/subject/body)는 self-contained(설계 §5) — 워커가 DB 재조회 불필요.
CREATE TABLE outbox (
    outbox_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id     BIGINT        NOT NULL REFERENCES notification_delivery(delivery_id) ON DELETE CASCADE,
    channel         VARCHAR(16)   NOT NULL,
    target          VARCHAR(512)  NOT NULL,
    subject         VARCHAR(255),
    body            VARCHAR(4000) NOT NULL,
    idempotency_key VARCHAR(255)  NOT NULL,
    status          VARCHAR(16)   NOT NULL DEFAULT 'PENDING',   -- PENDING / PUBLISHED / DLQ
    attempt_count   INT           NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- 릴레이가 발행 대상(PENDING, due)을 빠르게 긁어오는 인덱스.
CREATE INDEX idx_outbox_due ON outbox(status, next_attempt_at);
